bean_dev_tool:
    library_source: E:\wamp31\www\libraries\
    library_workspace: E:\wamp31\www\thuvien\dev-book\libraries\
    components: ~
    bundles:
        - BeanDevToolBundle
        - BeanBookBundle
        - BeanCreativeWorkBundle
        - BeanThingBundle

#imports:
#    - { resource: api_platform/resources.yaml }

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
#    resource_class_directories:
#        - '%kernel.project_dir%/libraries/bundle/BeanBookBundle/src'
