bean_dev_tool:
    library_source: E:\wamp31\www\libraries\
    library_workspace: E:\wamp31\www\thuvien\dev-book\libraries\
    components: ~
    bundles:
        - BeanDevToolBundle
        - BeanBookBundle
        - BeanCreativeWorkBundle
        - BeanThingBundle
        - MagentaCBookAdminBundle
        - MagentaCBookModelBundle