doctrine:
    dbal:
        types:
            magenta_json: Magenta\Bundle\CBookModelBundle\Doctrine\Types\JsonType
            json: Sonata\Doctrine\Types\JsonType

    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~

security:
    encoders:
        Magenta\Bundle\CBookModelBundle\Entity\User\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_ALLOWED_TO_SWITCH: ~
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # set access_strategy to unanimous, else you may have unexpected behaviors
    access_decision_manager:
        strategy: unanimous

    providers:
        magenta_user:
            id: magenta_user.user_provider.username


sonata_media:
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false


    # if you don't use default namespace configuration
    class:
        media: Magenta\Bundle\CBookModelBundle\Entity\Media\Media
        gallery: Magenta\Bundle\CBookModelBundle\Entity\Media\Gallery
        gallery_has_media: Magenta\Bundle\CBookModelBundle\Entity\Media\GalleryHasMedia
    db_driver: doctrine_orm # could be doctrine_orm, doctrine_mongodb or doctrine_phpcr