# api/config/api_platform/resources.yaml
resources:
    Magenta\Bundle\CBookModelBundle\Entity\Organisation\Organisation:
#        shortName: 'User'                   # optional
        description: 'Organisations' # optional
#        iri: 'http://schema.org/User'       # optional
        attributes:                          # optional
            pagination_items_per_page: 25    # optional
            normalization_context:
                groups:
                    - read_organisation
                    - read_creative_work
                    - read_thing
            denormalization_context:
                groups:
                    - write_organisation
        itemOperations:
            get: ~
    #        special:
    #            route_name: 'book_special'
            get_books:
                route_name: 'organisation_books'

    Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgBook:
        attributes:                          # optional
            order:
                id: DESC
            normalization_context:
                groups:
                    - read_book
                    - read_creative_work
                    - read_creative_work_partOf
                    - read_thing
            denormalization_context:
                groups:
                    - write_book
                    - write_creative_work
                    - write_creative_work_partOf
                    - write_thing
        itemOperations:
            get: ~
    #        special:
    #            route_name: 'book_special'
            get_chapters:
                route_name: 'organisation_book_chapters'
            get_root_chapters:
                method: 'GET'
                route_name: 'organisation_book_root_chapters'

    Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgChapter:
        attributes:                          # optional
            order:
                id: DESC
            normalization_context:
                groups:
                    - read_chapter
                    - read_creative_work
                    - read_thing
            denormalization_context:
                groups:
                    - write_chapter
                    - write_creative_work
                    - write_thing

    Magenta\Bundle\CBookModelBundle\Entity\User\User:
#        shortName: 'User'                   # optional
        description: 'App Users' # optional
#        iri: 'http://schema.org/User'       # optional
        attributes:                          # optional
            pagination_items_per_page: 25    # optional
            normalization_context:
                groups:
                    - read_user
            denormalization_context:
                groups:
                    - write_user