#Magenta\Bundle\CBookModelBundle\Entity\User\User:
#    attributes:
#        firstName:
#            groups: ['read_user','write_user']

#Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgBook:
#    attributes:
#        firstName:
#            groups: ['read_user','write_user']
