#Magenta\Bundle\CBookModelBundle\Entity\User\User:
#    attributes:
#        firstName:
#            groups: ['read_user','write_user']

Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrganisationMember:
    attributes:
        id:
            groups: ['read_member']
        organization:
            groups: ['read_organisation','write_organisation']
        person:
            groups: ['read_app_person','write_app_person']

Magenta\Bundle\CBookModelBundle\Entity\Organisation\OrgBook:
    attributes:
        id:
            groups: ['read_thing']

Magenta\Bundle\CBookModelBundle\Entity\Person\Person:
    attributes:
        id:
            groups: ['read_app_person']
        birthDate:
            groups: ['read_app_person','write_app_person']
        familyName:
            groups: ['read_app_person','write_app_person']
        givenName:
            groups: ['read_app_person','write_app_person']


#Magenta\Bundle\CBookModelBundle\Entity\Organisation\Organisation:
#    attributes:
#        logo:
#            groups: ['read_organisation','write_organisation']