bean_dev_tool:
    library_source: D:\workspace\libraries\cbook\
    library_workspace: D:\workspace\magenta\cbook\dev\libraries\
    components: ~
    bundles:
        - BeanDevToolBundle
        - BeanSonataMediaBundle
        - BeanBookBundle
        - BeanCreativeWorkBundle
        - BeanMediaBundle
        - BeanPersonBundle
        - BeanThingBundle
        - BeanOrganizationBundle
        - MagentaCBookAdminBundle
        - MagentaCBookModelBundle
        - MagentaCBookApiBundle
        - MagentaCBookMediaApiBundle
        - MagentaCBookJWTBundle
