magenta_book_login:
  path:      /login
  controller: MagentaCBookAdminBundle:BookReader:login
  defaults:   { format: reference }

magenta_book_index:
  path:      /{accessCode}/{employeeCode}
  controller: MagentaCBookAdminBundle:BookReader:index
  defaults:   { format: reference }

magenta_book_reader_book:
  path:      /{accessCode}/{employeeCode}/book/{bookId}
  controller: MagentaCBookAdminBundle:BookReader:readBook
  defaults:   { format: reference }

magenta_book_reader_chapter:
  path:      /{accessCode}/{employeeCode}/chapter/{chapterId}
  controller: MagentaCBookAdminBundle:BookReader:readChapter
  defaults:   { format: reference }

magenta_book_contact:
  path:      /{accessCode}/{employeeCode}/contact
  controller: MagentaCBookAdminBundle:BookReader:contact
  defaults:   { format: reference }
