magenta_book_login:
  path:      /login
  controller: MagentaCBookAdminBundle:BookReader:login
  defaults:   { format: reference }

magenta_book_index:
  path:      /{accessCode}/{employeeCode}
  controller: MagentaCBookAdminBundle:BookReader:index
  defaults:   { format: reference }

magenta_book_reader:
  path:      /{accessCode}/{employeeCode}/read
  controller: MagentaCBookAdminBundle:BookReader:reader
  defaults:   { format: reference }

magenta_book_contact:
  path:      /{accessCode}/{employeeCode}/contact
  controller: MagentaCBookAdminBundle:BookReader:contact
  defaults:   { format: reference }
