<?php

namespace Magenta\Bundle\CBookModelBundle\Entity\Classification;

use Bean\Component\Thing\Model\Thing;
use Doctrine\Common\Collections\ArrayCollection;
use Magenta\Bundle\CBookModelBundle\Entity\Book\BookCategory;
use Magenta\Bundle\CBookModelBundle\Entity\Classification\Base\AppCategory;
use Magenta\Bundle\CBookModelBundle\Entity\Organisation\GroupCategory;
use Sonata\ClassificationBundle\Entity\BaseCategory as BaseCategory;

//use Gedmo\Mapping\Annotation as Gedmo;
//use Sonata\TranslationBundle\Model\Gedmo\TranslatableInterface;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 * Gedmo\TranslationEntity(class="Application\Sonata\ClassificationBundle\Entity\CategoryTranslation")
 */

/**
 * @ORM\Entity
 * @ORM\Table(name="classification__category_item")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"book" = "Magenta\Bundle\CBookModelBundle\Entity\Classification\BookCategoryItem"})
 * @ORM\HasLifecycleCallbacks
 */
abstract class CategoryItem {
	/**
	 * @var integer|null
	 * @ORM\Id
	 * @ORM\Column(type="integer",options={"unsigned":true})
	 * @ORM\GeneratedValue(strategy="AUTO")
	 * // Serializer\Groups(groups={"sonata_api_read", "sonata_api_write", "sonata_search"})
	 */
	protected $id;
	/**
	 * @return int|null
	 */
	public function getId(): ?int {
		return $this->id;
	}
	
	public function __construct() {
	
	}
	
	/**
	 * @var Category
	 * @ORM\ManyToOne(targetEntity="Magenta\Bundle\CBookModelBundle\Entity\Classification\Category", inversedBy="items")
	 * @ORM\JoinColumn(name="id_category", referencedColumnName="id", onDelete="CASCADE")
	 */
	protected $category;
	
	/**
	 * @var Thing
	 * @ORM\ManyToOne(targetEntity="Bean\Component\Thing\Model\Thing")
	 * @ORM\JoinColumn(name="id_thing", referencedColumnName="id", onDelete="CASCADE")
	 */
	protected $item;
	
	/**
	 * @var integer
	 * @ORM\Column(type="integer", nullable=true, options={"default":0})
	 */
	protected $position;
	
	/**
	 * @return int
	 */
	public function getPosition(): int {
		return $this->position;
	}
	
	/**
	 * @param int $position
	 */
	public function setPosition(int $position): void {
		$this->position = $position;
	}
	
	/**
	 * @return Category
	 */
	public function getCategory(): Category {
		return $this->category;
	}
	
	/**
	 * @param Category $category
	 */
	public function setCategory(Category $category): void {
		$this->category = $category;
	}
	
	/**
	 * @return Thing
	 */
	public function getItem(): Thing {
		return $this->item;
	}
	
	/**
	 * @param Thing $item
	 */
	public function setItem(Thing $item): void {
		$this->item = $item;
	}
}
